(define (problem sussman-anomaly)
  (:domain blocks)
  (:objects a b c - block
  	    x y z - location
  	    arm - actor)
  (:init (on c a)
  	 (ontable a x)
	 (ontable b y)
	 (clear c)
	 (clear b)
	 (clear z)
	 (handempty arm))
  (:goal (and (on b c)
  	      (on a b)
	      (handempty arm))))
