(define (problem sussman-anomaly)
	(:domain blocks)
	(:objects a b c - block
        	  x y z - location)
	(:init (probabilistic 0.7 (on c a))
	       (probabilistic 0.3 (on c b))
	       (probabilistic 0.3 (on a b))
	       (probabilistic 0.3 (on a c))
	       (probabilistic 0.3 (on b a))
	       (probabilistic 0.3 (on b c))
	       (probabilistic 0.7 (ontable a x))
	       (probabilistic 0.3 (ontable a y))
	       (probabilistic 0.3 (ontable a z))
	       (probabilistic 0.3 (ontable b x))
	       (probabilistic 0.7 (ontable b y))
	       (probabilistic 0.3 (ontable b z))
	       (probabilistic 0.3 (ontable c x))
	       (probabilistic 0.3 (ontable c y))
	       (probabilistic 0.3 (ontable c z))
	       (probabilistic 0.3 (clear a))
	       (probabilistic 0.7 (clear b))
	       (probabilistic 0.7 (clear c))
	       (probabilistic 0.3 (clear y))
	       (probabilistic 0.3 (clear x))
	       (probabilistic 0.7 (clear z))
	       (probabilistic 0.7 (handempty))
	       (probabilistic 0.3 (holding a))
	       (probabilistic 0.3 (holding b))
	       (probabilistic 0.3 (holding c)))
	(:goal (and (on b c)
	       (on a b)
	       (handempty))))